#ifndef MODS_WALUIGI_CHARACTER_H
#define MODS_WALUIGI_CHARACTER_H

enum WaluigiCharacterId {
    WALUIGI_CHARACTER_MARIO = 0,
    WALUIGI_CHARACTER_LUIGI = 1,
    WALUIGI_CHARACTER_WARIO = 2,
    WALUIGI_CHARACTER_YOSHI = 3,
    WALUIGI_CHARACTER_WALUIGI = 4,
    WALUIGI_CHARACTER_COUNT = 5
};

#endif
